### ISSUE TITLE
[Bug Report] v-checkbox & v-radio can toggle only when i clicked component's label

### ISSUE THREAD

**Issue by armadillo-dev** [vuetifyjs/vuetify#10462]
### Environment
**Vuetify Version:** 2.2.9
**Vue Version:** 2.6.11
**Browsers:** Chrome 79.0.3945.130
**OS:** Mac OS 10.14.6

### Steps to reproduce
1. go to reproduction link
2. click checkbox input or radio input

### Expected Behavior
toggle component(v-checkbox or v-radio)

### Actual Behavior
not working

### Reproduction Link
<a href="https://codepen.io/armadillo-dev167/pen/eYNOPKy?editable=true" target="_blank">https://codepen.io/armadillo-dev167/pen/eYNOPKy?editable=true</a>

### Other comments
i can toggle only when i clicked component's label

**Comment by adarshmadrecha** [comment]
Even after v2.2.10, having this issue.

**Comment by vlourme** [comment]
Getting this too, the select control click seems offset.
<img width="315" alt="Capture d’écran 2020-02-06 à 13 36 24" src="https://user-images.githubusercontent.com/58728578/73937627-bdf6cc00-48e5-11ea-9105-e914e85fa55f.png">
(Only the red zone can be clicked on my tests, only around borders is clickable)

**Comment by denozavr** [comment]
As a temporary fix, which helped me, you could use the next CSS globally (if all your radios/checkboxes have default `ripple=true`)

```
     .v-input--selection-controls__ripple{
        z-index: 1;
    }
```

**Comment by KaelWD** [comment]
If all your checkboxes have `ripple=true` then update vuetify, if not then wait for 2.2.11

**Comment by armadillo-dev** [comment]
I fixed this issue after update to 2.2.10
thx you!!

**Comment by rlemaigre** [comment]
I'm not sure if I should open a new issue or if it is proper to comment an old one, but this is still not working for me with Vuetify 2.2.18 (tested in Chrome and Firefox). It seems the ripple is hiding the checkbox. Only the temporary fix mentioned above resolved the issue.

**Comment by jacekkarczmarczyk** [comment]
I can't reproduce this particular issue after updating vuetify to 2.2.18, but if you can please create a new one

**Comment by azalpacir** [comment]
Updated to **version 2.2.22**, still getting the same issue.

**Comment by rlemaigre** [comment]
I remember that deleting my node_modules folder and package-lock.json, then reinstalling all the dependencies solved the problem for me a month ago when I commented this issue. Or perhaps it is something else I did, I don't know. Just something to try...

**Comment by azalpacir** [comment]
Thanks will try, i did check the node_modules in the browser it got updated to the said version.

**Comment by azalpacir** [comment]
> I remember that deleting my node_modules folder and package-lock.json, then reinstalling all the dependencies solved the problem for me a month ago when I commented this issue. Or perhaps it is something else I did, I don't know. Just something to try...

Still didn't work :(

**Comment by hansenconnor** [comment]
This appears to still be broken - fix above solves the issue
     .v-input--selection-controls__ripple{
        z-index: 1;
    }
