### ISSUE TITLE
[Bug Report][3.0.0-alpha.11] Sass error caused by `VList.sass` and `VListItem.sass` both forwarding the same variables

### ISSUE THREAD

**Issue by glen-84** [vuetifyjs/vuetify#14407]
### Environment
**Vuetify Version:** 3.0.0-alpha.11
**Vue Version:** 3.2.21
**Browsers:** Chrome 95.0.4638.69
**OS:** Windows 10

### Steps to reproduce
Follow the README.

**IMPORTANT:** This is `alpha.11` – if you switch to `3.0.0-next-20211105.0`, for example, this error goes away, but the `.cache/vuetify/styles.scss` file appears to include far too many of the Sass files (maybe all of them?) – is that another issue, or did I do something wrong?

### Expected Behavior
No errors, able to customise v-tooltip and other components' Sass variables.

### Actual Behavior
`SassError: This module was already loaded, so it can't be configured using "with".`

### Reproduction Link
<a href="https://github.com/glen-84/vuetify-loader-issue" target="_blank">https://github.com/glen-84/vuetify-loader-issue</a>

**Comment by KaelWD** [comment]
> far too many of the Sass files

There was an extra import in VList, should be fixed in `3.0.0-next-20211117.0`

**Comment by glen-84** [comment]
Yep, that issue is fixed, but unfortunately a production build still shows the Sass error. 😞

Simply removing the `@forward` might not be enough.

**Comment by glen-84** [comment]
I'm no longer able to reproduce this error. Closing.

**Comment by glen-84** [comment]
@KaelWD,

I'm still seeing this in my "real" application. I've noticed that the `@forward`s appear to be ordered differently after each dev build. What's even stranger is that between builds, the number of forwards can change – `VResponsive` was imported in `.cache/vuetify/styles.scss`, I cleaned, ran start again, and it was removed. This may be the reason why I thought that the issue was fixed in my repro repository.

I'll try to repro it again tomorrow in that repository.

**Comment by glen-84** [comment]
Ya it's still happening. 😭

https://github.com/glen-84/vuetify-loader-issue/tree/vlist-issue

**Comment by glen-84** [comment]
It doesn't seem to happen when using manual imports.
