### ISSUE TITLE
[Bug Report][3.0.0-alpha.12] v-card-text opacity: var(--v-medium-emphasis-opacity);

### ISSUE THREAD

**Issue by volarname** [vuetifyjs/vuetify#14696]
### Environment
**Vuetify Version:** 3.0.0-alpha.12
**Last working version:** 2.6.3
**Vue Version:** 3.2.30
**Browsers:** Chrome 97.0.4692.99
**OS:** Windows 10

### Steps to reproduce
put anything to v-card-text and weird opacity is applied

### Expected Behavior
no opacity, only padding and font style/size change

### Actual Behavior
weird opacity is applied to everything in v-card-text

### Reproduction Link
<a href="https://codepen.io/volarname/pen/QWOdpvr" target="_blank">https://codepen.io/volarname/pen/QWOdpvr</a>

**Comment by BlueBazze** [comment]
You are right.
I dont know the idea behind the opacity.
Taking a look through the examples & theming from material design.
https://material.io/components/cards#theming
It seems like the body text is meant to adopt part of the surface color.
The original color on v-card-text is --v-theme-on-surface which by default is #fff

Most likely the idea behind this. By making the text a bit transparent makes it tinted with surface color.
If you had a strong color for surface, and white text. The text would be slightly tinted.

Dont know if this is the intended behavior and reasoning behind the opacity. But the color tinting is common in material design from what i have seen.

**Comment by volarname** [comment]
its just different behavior  than in v2, that it affect all content in `v-card-text`
if its wanted feature, put it please into documentation, that in `v-card-text`all content is tinted
i will stick with `<div class='pt-x'></div>` for padding or  `<div class='mt-x'></div>` for margin

**Comment by johnleider** [comment]
this is fixed as of latest nightly

**Comment by pabrul** [comment]
Hello,

I am writing to report that the bug initially identified in Vuetify version 3.0.0-alpha.12, documented in issue [#14696](https://github.com/vuetifyjs/vuetify/issues/14696) regarding the v-card-text opacity, is still present in the latest version of Vuetify (3.3.0) that I am currently using.

The issue, which pertains to the v-card-text having an opacity set as var(--v-medium-emphasis-opacity);, continues to affect the visual presentation in my applications.

I wanted to bring this to your attention as it seems to be an ongoing issue that might require further investigation or a potential fix in the upcoming releases.

Thank you for your continued efforts in improving Vuetify.

**Comment by johnleider** [comment]
We have two potential approaches for implementing opacity on v-card-text, each with its own set of implications:

Specify a Text Color and Opacity:
By setting a specific text color and opacity, we can directly control the appearance of the text. However, this approach has a downside: it prevents the text from inheriting colors from the parent. This can lead to issues when switching between different themes, such as dark and light modes, where text color needs to adjust accordingly.

Specify Only an Opacity:
This option allows for setting a general opacity that applies to everything within v-card-text. While this maintains color inheritance from the parent, it also means that not just the text, but all contents of v-card-text (like icons, images, etc.) will have reduced opacity. This could affect the overall visual clarity and may not be desirable in all cases.

Currently, there's no one-size-fits-all solution that satisfies all requirements without compromise. It's a trade-off between maintaining theme adaptability and having uniform opacity across all elements within v-card-text. We're open to suggestions and further discussion to find the most balanced approach for this feature.
