### ISSUE TITLE
[Bug Report][3.0.0] VImg (w/ eager) error in async component

### ISSUE THREAD

**Issue by andrewspy** [vuetifyjs/vuetify#15832]
### Environment
**Vuetify Version:** 3.0.0-beta.11
**Vue Version:** 3.2.39
**Browsers:** Chrome 105.0.0.0
**OS:** Windows 10

### Steps to reproduce
- Open reproduction in [stackblitz](https://stackblitz.com/edit/nuxt-starter-x2nqsv?file=pages/index.vue).
- See console log error.

Console error as below:
```
Uncaught (in promise) TypeError: Cannot destructure property 'naturalHeight' of 'img' as it is undefined.
    at poll (VImg.tsx:162:32)
    at pollForSize (VImg.tsx:175:7)
    at VImg.tsx:138:35
```

### Expected Behavior
No error with `eagar` option

### Actual Behavior
Error with `eager` option

### Reproduction Link
<a href="https://stackblitz.com/edit/nuxt-starter-x2nqsv?file=pages/index.vue" target="_blank">https://stackblitz.com/edit/nuxt-starter-x2nqsv?file=pages/index.vue</a>

### Other comments
- As an async component, `image` element is undefined when use with `eager` option.

**Comment by jthn** [comment]
I'm not sure if this is useful or not, but I am also getting this error when mounting a component with @vue/test-utils using vitest in a jsdom environment.

**Comment by Antoine340** [comment]
> I'm not sure if this is useful or not, but I am also getting this error when mounting a component with @vue/test-utils using vitest in a jsdom environment.

I've fixed the problem by adding aspect-ratio to v img, I guess it's coming from the component not being lazy loading without it

**Comment by DiegoAlessandro** [comment]
I get this error even with vue3+vitest+vuetify 3.4.0. Has anyone else encountered the same phenomenon?

**Comment by kosukhin** [comment]
@DiegoAlessandro I think it was fixed in version 3.4.1

I made [playground](https://play.vuetifyjs.com/#eNq1VE2PmzAQ/SsjLrBtYrKbSpVQErXaUw9RL70lObgwBO8a27JNPrTiv3cMhKBWldrDcsD2+L03n/LuLXI2T78aw04NRlm08lgbyT1u9gpg9bPxXiv4kkuRv673kUWpefGt5kd0+2jzXeEq7TH/hP9x1v+Hryz+5qEQp7ACZK94JUYs6qOL4SOIjsQkqqOv9lEPyiV3jlDFvJR4gfCbny038NI4L8rr3Bme45xb3aiiJ3VuyNFpTsr9HsD5q0TSOYvCVxk8LRbmcvMxhkJ4JgaV8J3mpba9HYQaApywqPIDq7HyZk/7NFPKk3ardNIPOrrcCuM7iKiNth7eQKstRe+xmIHFEloora4hpn7GgQOAlw5ZYMkbSYzeUcE9zyB5gPUGksFGquTPZbC7nYEceOElZhA/hybBFmNoZ+95D09TxGHYtQ/DxqFvDMU9xpxr5fxQXliHIiS7w0Of+/1+OlqE4u6q8iH9UanHaolM6mMS95SYpKbXQcqZIHHmwkOJPq+SuPLeuCxNX5xW1LAcKy0LtMxfjch1gSzXdWoq7bX7UzDM8CgY1FmQSSa4YbpPXDZIyEBgjuqFyWIGW+4rZrkqdE0JfYDHxWKktvc6jIOS/CX5m/97oe4htJOCWuqAVVNmH96kq1OR0UyxdEtnoMMqHec5mnUP0bOuby9R1M6iJVuyz3S1ZJ/YY3T4BbwMcMU=)

If choose version 3.4.0 and fast click to one-two-three. Error will happen.
But in version 3.4.1 it is no error.
![image](https://github.com/vuetifyjs/vuetify/assets/109918884/10093acf-9d2a-4abe-9d70-5a2803fc526d)

**Comment by PWie** [comment]
I can confirm that after upgrading to v3.4.1 the error when mounting VImg via @vue/test-utils using vitest in a jsdom environment is no longer happening 👍

**Comment by custer7** [comment]
me too. v3.5.8

**Comment by samerdraidi** [comment]
I am still facing this issue on v3.7.5

**Comment by UnSpiraTive** [comment]
@userquin When we turn on pageTransition in Nuxt 3, this issue still appears:

`app: {
    pageTransition: { name: "slide-right", mode: "out-in" },
}`

**Comment by hahatulk** [comment]
why is this even closed? issue persists

**Comment by ericirish** [comment]
Still experiencing this with Nuxt SSG builds.

**Comment by al1maher** [comment]
Still facing this issue

> why is this even closed? issue persists

Found a solution?
