### ISSUE TITLE
[Bug Report][3.1.4] useDisplay v-if Hydration node mismatch

### ISSUE THREAD

**Issue by augnustin** [vuetifyjs/vuetify#16825]
### Environment
**Vuetify Version:** 3.1.4
**Vue Version:** 3.2.47
**Browsers:** Chrome 110.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
1.  `import { useDisplay } from "vuetify";`
2. `const { mobile } = useDisplay();`
3. `<div v-if="mobile">Whatever markup</div>`
4. Load page with SSR with a reduced screen (mobile) so that on the server `mobile == false` while on the client `mobile == true`

### Expected Behavior
While doing SSR, `mobile` should be `false`, but when hydrating, the value change should be taken in account and generate a re-rendering.

### Actual Behavior
I get a 

```
chunk-3NMN3MUW.js?v=ca98b82d:1381 [Vue warn]: Hydration node mismatch:
- Client vnode: Symbol(Comment) 
- Server rendered DOM: <!--[--> (start of fragment) 
  at <VDefaultsProvider defaults= {VTabs: {…}} > 
  at <VToolbar ref=Ref< undefined > class="v-app-bar top-screen" style= {top: '0px', zIndex: 1004, transform: 'translateY(0%)', position: 'fixed', height: undefined, …}  ... > 
  at <VAppBar color="white" class="top-screen" flat=true  ... > 
  at <Header top-transparent=true > 
  at <PageWrapper no-container="" > 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouteProvider key="/" routeProps= {Component: {…}, route: {…}} pageKey="/"  ... > 
  at <FragmentWrapper > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <VApp> 
  at <Default > 
  at <LayoutLoader key="default" name="default" hasTransition=false > 
  at <FragmentWrapper > 
  at <NuxtLayout> 
  at <App key=2 > 
  at <NuxtRoot>
```
warning and then the app stops being reactive.
My guess is that the error comes from the `v-if="mobile"` which produces different markup in the frontend and the backend.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqVUFtLwzAU/ishTwprgxcQZtUJPvgy/AHLHrL2VOOaC0laGaP/3ZNeRu1EsH1oz+W7nc2RPlubNjXQJc0CKFuJAI9cE5I1ibC2+x2LZCfc0Ji2Ei2aROZGE/yUD5wqs5MVcErYCGdzPKKVkBorHuKbjUrxeT0UTgSJhOCccU8nSXbyg4QD/sSO/xmbRMDS507aQDyEOo6lssYFciS1hxfpcfFAWlI6owineIMgywOn9xGKaTxu9kla8jCBXFxONqRfdytr0PWbBY2bpag8dCsZ6w2gNF3QXh1t2/TTG40HP0b3fBh4Tpek68Qeuok1px8hWL9krNZ2/57mRrEVzpirdZAKksKo1U16nd7esUL6MO2n4FWyc+bLg0NFThcT8j7q7wLDGHmv0oF2aCWV2PnIe8bHUKQBlzjQBThwf5qf7f4IMJudhYiaLdctHrSSeu9nt8x9d8fNaO3/6TqGCN9GlXZBe3eo1yHo9htpFhFo)

### Other comments
The error doesn't appear on the reproduction link because I don't know how to make SSR with it, but it is the same code :(

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/getting-started/installation/#ssr

**Comment by augnustin** [comment]
Thanks @KaelWD for getting back.

I haven't mentioned it, but in my vuetify plugin definition, I have:

```
import { createVuetify } from "vuetify";

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(
    createVuetify({
      ssr: true,
    })
  );
});
```

That said, I still have the impression there is a bug with the `const {mobile} = useDisplay();` prop. 

On page load, properties like `const {smAndDown} = useDisplay();` are set to `false`, which makes sense (whichever value actually) and they don't trigger any hydration error, while `mobile` does in a `v-if`.

I guessing from your comment that you don't want to support frameworks like nuxt which is a strong though acceptable assumption, but if I'm wrong, I would consider this is worth further investigation.

I managed to find a way out of this using `smAndDown` along with `d-sm-none` classes, so I'm good, but I wanted to help as I find Vuetify awesome!

Best

**Comment by KaelWD** [comment]
`platform` and `mobile` aren't respecting `ssr` during hydration

**Comment by augnustin** [comment]
Let me know if I can try to investigate on this. I tried to look at the code but it hasn't been obvious how `mobile` is different from `smAndDown` at first read.

**Comment by davidstackio** [comment]
I'm running into the same issue except with `xs` instead of `mobile`. I'm using vuetify v3.3.8 and `ssr: true` in my plugin config (using Nuxt v3.6.3). This only started happening when I updated some packages from ~ April, so maybe related to Vue 3.3.

Steps to reproduce:
1. `import { useDisplay } from "vuetify";`
2. `const { xs } = useDisplay();`
3. `<div v-if="xs">Whatever markup</div>`
4. Load page with SSR with a reduced screen (mobile) so that on the server `mobile == false` while on the client `mobile == true`.

@KaelWD I can open a new issue if needed.

**Comment by Chantal5** [comment]
Just ran into this problem with Nuxt 3.8.2 and Vuetify 3.4.3. Am I doing anything wrong?

I have:
- No `ssr: true` in plugin config (Threw some other error, so I removed it. Should be true by default anyway. Vuetify docs don't mention it.)
- `import { useDisplay } from 'vuetify'` (also, why is Nuxt auto-import not working here? I have `autoImport: true`)
- `const display = ref(useDisplay())`
- `<div v-if="display.smAndDown">Whatever markup</div>`

Everything seems to be working as it should, I just get the warning, but I'd like to keep a clean console :-)

**Comment by Flashx29** [comment]
Vuetify 3.4.4 & Nuxt 3 -> adding ssr: true in createVuetify({ ssr: true }) worked for me
fixed this console error: [Vue warn]: Hydration node mismatch + useDisplay() was not working properly

**Comment by davidstackio** [comment]
@Chantal5 If using Nuxt and you want auto imports, check out the new [vuetify-nuxt-module](https://vuetify-nuxt-module.netlify.app/).

**Comment by keupsonite** [comment]
I suggest to use `@nuxtjs/device` for SSR mobile detection since not working with vuetify.

```import { useDisplay } from "vuetify";

export const useMobileDevice = (): ComputedRef<boolean> => {
  const { platform, mobile } = useDisplay();
  const { isMobile: isSSRMobile } = useDevice();

  return computed(() => {
    return platform.value.ssr ? isSSRMobile : mobile.value;
  });
};
```

**Comment by tilenpirih** [comment]
I still have this bug and I'm using "vuetify": "^3.5.8" and "nuxt": "^3.8.2",

if found a solution that works but it's not that pretty. if I just add a promise that waits 1ms it works. 

```
const drawer = ref(false)

onMounted(async () => {
  await new Promise(resolve => setTimeout(resolve, 1)) // add this
  if (display.value.lgAndUp)
    drawer.value = true
})
```

**Comment by johnleider** [comment]
> I still have this bug and I'm using "vuetify": "^3.5.8" and "nuxt": "^3.8.2",
> 
> if found a solution that works but it's not that pretty. if I just add a promise that waits 1ms it works.
> 
> ```
> const drawer = ref(false)
> 
> onMounted(async () => {
>   await new Promise(resolve => setTimeout(resolve, 1)) // add this
>   if (display.value.lgAndUp)
>     drawer.value = true
> })
> ```

What version of Vue?

**Comment by ipanamski** [comment]
Adding `ssr: true` fixed it for me.
