### ISSUE TITLE
[Bug Report] Data Table unnecessary pagination watch trigger

### ISSUE THREAD

**Issue by eolant** [vuetifyjs/vuetify#3585]
### Versions and Environment
**Vuetify:** 1.0.8
**Vue:** 2.5.7
**Browsers:** Chrome 64.0.3282.167
**OS:** Mac OS 10.11.3

### Steps to reproduce
Slightly modified [template](https://next.vuetifyjs.com/en/components/data-tables#example-server)
When using with server side data `totalItems` can often change which causes update of the property in pagination object which triggers watch handler and creates unnecessary API call that returns exactly the same data.

### Expected Behavior
`totalItems` shouldn't be in pagination object. There should be only one API call that returns relevant data.

### Actual Behavior
Unnecessary watch trigger that creates API call that returns the same data.

### Reproduction Link
[https://codepen.io/anon/pen/wmWmZy](https://codepen.io/anon/pen/wmWmZy)

### Other comments
Issue wasn't present in beta 6 as `pagination.totalItems` was always `0`. In version 1.0.8 it updates when you assign new set of items to it which in return also causes watch handler to trigger.

**Comment by ljyf5593** [comment]
I trigger this bug too

**Comment by isimonov** [comment]
I acknowledge the error. totalItems should not be in the pagination object. Otherwise, why do we pass a special property totalItems (: total-items = "totalItems") in the v-data-table component? In the pagination object, the totalItems property is not used and is not needed.

**Comment by canhkieu** [comment]
Got the same problem.

**Comment by nekosaur** [comment]
There definitely was a reason for having totalItems in pagination (parallel to totalItems prop). I'm not totally sure if there still is. But it might not be as easy as just removing it.

**Comment by canhkieu** [comment]
> totalItems shouldn't be in pagination object
I think totalItems is not necessary. We alway have total from server-side.

**Comment by eolant** [comment]
@nekosaur I've searched the repo code for `totalItems` and the only place it's used is in `mixins/data-iterable.js` and the only function of this property is to be inited and updated. Seems unnecessary to me.

**Comment by canhkieu** [comment]
```javascript
 computed: {
    params() {
      return {
        page: this.pagination.page || null,
        limit: this.pagination.rowsPerPage || null,
        sort: this.pagination.sortBy || null,
        order: this.pagination.descending || null,
      };
    }
  },
  watch: {
    params(val, oldVal) {
      if (JSON.stringify(val) !== JSON.stringify(oldVal)) this.fetchData(val);
  }
```
Temporary fix

**Comment by eolant** [comment]
@canhkieu I would rather just go back to older version since doing this for 10 or more components would be painful :D

**Comment by canhkieu** [comment]
@eolant really painful. Backed to older version.

**Comment by eolant** [comment]
I actually have tried to fix it myself by deleting `totalItems` from `pagination` object. It doesn't break anything nor fixes the issue as calls made 2 times anyway with the identical properties in the Object. Unfortunately I don't have much time to investigate it further.

**Comment by isimonov** [comment]
Any such attempt to correct current behavior will be unnatural and cumbersome. In my opinion, this problem should be solved by developers in the code of the Data Table component itself.

**Comment by canhkieu** [comment]
Waiting for @nekosaur solution. ^_^

**Comment by nekosaur** [comment]
1.1 will include a workaround fix for this. By using new prop `disable-page-reset` there should be no more doubled updates to pagination object.

**Comment by canhkieu** [comment]
It's still not fix. I tried but not thing change. It's still duplicate request at first time
```
:disable-page-reset="true"
```

First request
```
descending:false
page:1
rowsPerPage:10
sortBy:name
totalItems:0
```

Second request
```
descending:false
page:1
rowsPerPage:10
sortBy:name
totalItems:32
```

**Comment by canhkieu** [comment]
It's still not fix. I tried but not thing change. It's still duplicate request at first time
```
:disable-page-reset="true"
```

First request
```
descending:false
page:1
rowsPerPage:10
sortBy:name
totalItems:0
```

Second request
```
descending:false
page:1
rowsPerPage:10
sortBy:name
totalItems:32
```

**Comment by canhkieu** [comment]
Update to 1.1.0-alpha.4 so terrible. It's 3 times requests
![deepinscreenshot_select-area_20180516152151](https://user-images.githubusercontent.com/136077/40105516-5bd6c642-591d-11e8-8f95-1eb6ced2b6cc.png)

**Comment by isimonov** [comment]
There are questions to the component Data Table, the proposed solutions are somewhat like crutches, still not working, unfortunately...

**Comment by nekosaur** [comment]
PR is still open. Will hopefully make it into 1.1

**Comment by jordandc1** [comment]
Fixed?

**Comment by nekosaur** [comment]
In v1.1.0-alpha.6

**Comment by fontenele** [comment]
i was binding :total-items="pagination.totalItems"
then when getting results i was setting this.pagination.totalItems so it makes two requests.

to fix a created the totalItems at return of data()
then bindind  :total-items="totalItems"
then when getting results this.totalItems = res.total

this works for me.
