### ISSUE TITLE
Slider bringing up keyboard and cursor after tap on mobile

### ISSUE THREAD

**Issue by sebastiaan-de-vries** [vuetifyjs/vuetify#4957]
**This bug was reported and solved for Vuetify 1.1.0-alpha.4 (bug #4062), but it seems to have reappeared in Vuetify 1.2.0-alpha-3.**

### Versions and Environment
Vuetify: 1.2.0-alpha.3
Vue: 2.5.17
Browsers: Safari & Chrome
OS: iOS 11

### Steps to reproduce
Tap on the slider from a mobile device (tested with IPhone SE and IPhone X - both on iOS 11)

### Expected Behavior
Slider moves to the position of the tap.

### Actual Behavior
Slider moves but also the keyboard comes up and a cursor shows up on the left side of the slider (likely due to the input element underneath)

### Reproduction Link
[https://codepen.io/CPSebastiaan/pen/pOgaqJ](https://codepen.io/CPSebastiaan/pen/pOgaqJ)

**Comment by sebastiaan-de-vries** [comment]
When I first mentioned this bug, it was in an Alpha version, so I can imagine that it has disappeared of the radar.

However, the slider component is quite useless on iOS devices, because of this bug. When the cursor appears, and it often does, the component stops responding at all... I really hope this bug is fixable! Thanks for all your efforts on this the great framework! Today, I published my first [Web App](https://app.planhr.nl) with it -> could not have done it without your work!

**Comment by BenShelton** [comment]
The cursor issue is also still a problem in IE11.

A fix for just the cursor is to just shift it way off screen (thanks https://stackoverflow.com/a/29146606/7542390):

```stylus
.v-slider input
  text-indent: -9999em
```

However if on iOS this shows the keyboard I doubt this'll help.
