### ISSUE TITLE
[Bug] Conflicting order between styles

### ISSUE THREAD

**Issue by Djaler** [vuetifyjs/vuetify#5271]
Version and Environment
Vuetify: v1.3.0-beta.0
Vue: 2.5.17
OS: Linux

I see this warnings:
```
chunk cards_import~subscribers_alert [mini-css-extract-plugin]
Conflicting order between:
 * css ./node_modules/css-loader??ref--11-oneOf-3-1!./node_modules/postcss-loader/lib??ref--11-oneOf-3-2!./node_modules/stylus-loader??ref--11-oneOf-3-3!./node_modules/vuetify/src/stylus/components/_select.styl
 * css ./node_modules/css-loader??ref--11-oneOf-3-1!./node_modules/postcss-loader/lib??ref--11-oneOf-3-2!./node_modules/stylus-loader??ref--11-oneOf-3-3!./node_modules/vuetify/src/stylus/components/_selection-controls.styl
```

**Comment by KaelWD** [comment]
vuetify-loader?

**Comment by Djaler** [comment]
yes

**Comment by usercao** [comment]
@KaelWD I also meet this bug when I build the project，may I ask you how this bug produce？And how to solve this problem？Thanks.

**Comment by hareku** [comment]
I have same problem.

```
WARNING in chunk 0 [mini-css-extract-plugin]
Conflicting order between:
 * css ./node_modules/css-loader??ref--7-oneOf-1-1!./node_modules/postcss-loader/src??ref--7-oneOf-1-2!./node_modules/stylus-loader??ref--7-oneOf-1-3!./node_modules/vuetify/src/stylus/components/_text-fields.styl
 * css ./node_modules/css-loader??ref--7-oneOf-1-1!./node_modules/postcss-loader/src??ref--7-oneOf-1-2!./node_modules/stylus-loader??ref--7-oneOf-1-3!./node_modules/vuetify/src/stylus/components/_textarea.styl
 * css ./node_modules/css-loader??ref--7-oneOf-1-1!./node_modules/postcss-loader/src??ref--7-oneOf-1-2!./node_modules/stylus-loader??ref--7-oneOf-1-3!./node_modules/vuetify/src/stylus/components/_cards.styl
```

**Comment by KaelWD** [comment]
See https://github.com/vuetifyjs/vuetify-loader/releases/tag/v1.0.3

**Comment by Djaler** [comment]
@KaelWD can you pleast suggest, how can I replace it with vue-style-loader?

**Comment by xhubert** [comment]
Same question.
Solved by importing those relative components used in pages.

I used the `v-data-table` in a certain page, but I didn't import it while initializing the Vuetify in plugin.

Hope it helpful.

**Comment by sinitsyn-alex** [comment]
@KaelWD can you pleast suggest, how can I replace it with vue-style-loader?
I use a-la-carte (css-loader, style-loader, stylus, stylus-loader, vuetify-loader)

**Comment by Djaler** [comment]
@KaelWD can you help us?

**Comment by ocavue** [comment]
If you are using Vue CLI v3, add the code below to `vue.config.js` can ignore this error.

```js
// vue.config.js
module.exports = {
    css: {
        extract: { ignoreOrder: true },
    },
}
```

Make sure that you have install the latest `mini-css-extract-plugin`, which is a dependency of `@vue/cli-service`.

Check https://github.com/webpack-contrib/mini-css-extract-plugin/issues/250 and https://cli.vuejs.org/config/#css-extract for more information.

**Comment by JohnMica** [comment]
> If you are using Vue CLI v3, add the code below to `vue.config.js` can ignore this error.
> 
> ```js
> // vue.config.js
> module.exports = {
>     css: {
>         extract: { ignoreOrder: true },
>     },
> }
> ```
> 
> Make sure that you have install the latest `mini-css-extract-plugin`, which is a dependency of `@vue/cli-service`.
> 
> Check links below for more information:
> 
> * [webpack-contrib/mini-css-extract-plugin#250](https://github.com/webpack-contrib/mini-css-extract-plugin/issues/250)
> * [webpack-contrib/mini-css-extract-plugin#422](https://github.com/webpack-contrib/mini-css-extract-plugin/pull/422)
> * https://cli.vuejs.org/config/#css-extract

the only problem with this 'hack' is the order of the extracted CSS files would make the page load (on slower speed) really ugly and force the DOM to rearrange the whole thing once resources are loaded.
compute power wasted for no real reason :(

unless you guys managed to get all things sorted since this is now closed ? (I still don't have it working properly in nuxtjs with the latest release)

**Comment by 951759534** [comment]
zan

**Comment by Nsandomeno** [comment]
In researching this there seem to be two cases: 1 - where re-arranging nested components solves the issue and 2 - where `css-loader`, `postcss-loader`, `sass-loader`, and a `vuetify component style sheet` conflict in some way. Does order matter in both cases to the same extent? @JohnMica have you discovered any more on this?

**Comment by JohnMica** [comment]
@Nsandomeno i haven't discovered a way to fix this totally. 
My fix consisted in loading a few styles in my "global CSS" file and even if there is duplication of styles, there are only the Grid and a few other thing needed. 
Haven't tried with a new project - this use buefy or no component library at all.

**Comment by m4heshd** [comment]
Reordering hundreds of nested imports manually is insane just so we can satisfy the loader (I know about the performance improvements). But yeah, reordering works. I'm sticking with `ignoreOrder: true` even though I'm noticing the issues @JohnMica mentioned. But I can live with that.
