### ISSUE TITLE
Dense list compliance fix

### ISSUE THREAD

**Issue by basejump** [vuetifyjs/vuetify#616]
Very exciting lib to work with. Well done!

### Description
Dense setting on lists does not properly shrink the height and width size on icons, avatars and checkboxes

### Steps to reproduce
go to example 5 for best coverage in the docs. https://vuetifyjs.com/components/lists

### What is expected?
should shrink to follow specs here. 
https://material.io/guidelines/components/lists.html#lists-specs
li height: 48px
avatar to 38x38
icon font size to 20px from 24
subheader should drop to 40px height
list group subheader to 32px.

### Here is the fix we are using

```
.list
  &--dense
    .subheader
      font-size: 12px //on non-dense this goes from 16 to 14px. knock it down from 13 to 12 for dense
      height 40px
    .list--group
      .subheader
        height 32px ////knock down by 8px from the 40ps dense. "compact" setting like gmail
    .list__tile--avatar
      height: 48px
    .list__tile__avatar
      .icon, img
        height: 38px
        width: 38px
        font-size: 20px
    .list__tile__action
        .icon
          font-size: 20px

//for other areas that need to shrink to match material.io sizing
i.sm
  font-size: 20px

//xs icon font-size for gmail like toolbar buttons
i.xs
  font-size: 16px
```
see https://github.com/vuetifyjs/vuetify/issues/618

here is screen shot with example in https://github.com/basejump/vuetifyjs-docs/tree/616-dense-list-example

![image](https://cloud.githubusercontent.com/assets/187726/26526740/3df75280-4349-11e7-88f5-5cb1cb9b37f1.png)

**Comment by johnleider** [comment]
I've pushed some updates to branch fix/#616. Everything should be in order with the exception of the ```v-list-group``` subheader. I cannot find anything within material.io stating it should be 32px in height. Any help would be appreciated.

**Comment by basejump** [comment]
nice! I could have been more clear in my comments on that 32dp. It was a guesstimate and based on what I saw somewhere else but don't recall where now. Like the font size, you are right,  it doesn't really specify what it should be on the sub list groups, it just looked better I thought and was more proportional.

**Comment by johnleider** [comment]
Very good point. If you wouldn't mind taking a look at that branch and let me know what you think.

**Comment by basejump** [comment]
see here. https://github.com/basejump/vuetifyjs-docs/tree/616-dense-list-example
look like its still not scaling down the icon on dense lists when I comment out the hack fix in main.styl. 
![image](https://cloud.githubusercontent.com/assets/187726/26559084/ff043bc6-4472-11e7-8757-543a2e9d6dcd.png)

did you want me to do a pull request to add this kitchen sink list example 11 to the docs? some variation of this would certainly be helpful for others as well as for testing.

**Comment by basejump** [comment]
also, as far as the subheader goes, shrinking it to 32 height in subgroups when dense is certainly debbatable, however I do see and firmly believe that the font size should be at least shrunk to 13px from 14 but should probably aprox follow the proportions of the normal (non-dense) and be taken to 12px.
