### ISSUE TITLE
v-btn with primary, light & disabled is invisible

### ISSUE THREAD

**Issue by Christilut** [vuetifyjs/vuetify#687]
### Versions
vuetify 0.12.6
vue 2.3.3

### What is expected ?
disabled button should be greyed out but visible

### What is actually happening ?
on white background, the disabled button is invisible
added a red background to clearly show the button (remove the red background to see the problem)

the `button workaround` is my current workaround

### Reproduction Link
https://codepen.io/anon/pen/zzYbBr

**Comment by johnleider** [comment]
That is the expected behavior. A light button has a #fff opacity background on disable. If your button is on a dark background, use dark.

**Comment by Christilut** [comment]
And if the colors were something like this? https://codepen.io/anon/pen/ZyEZBy

It's strange to me that a light button is invisible in any valid scenario.

**Comment by johnleider** [comment]
We will address this.

**Comment by johnleider** [comment]
This has been resolved on dev and will go out with next release.

**Comment by renztoygwapo** [comment]
is it fixed ?

**Comment by johnleider** [comment]
Yes

**Comment by renztoygwapo** [comment]
I still have the same issue, I installed the vuetify version 0.17.6. didnt load the correct color primary,success etc.

**Comment by KaelWD** [comment]
Make a new issue if it's still a problem.
